version: "3.8"
services:
    db:
        image: postgres:16
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
            POSTGRES_USER: odoo
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgresql-data:/var/lib/postgresql/data
            - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
        command: -c 'config_file=/etc/postgresql/postgresql.conf'
        networks:
            - backend
        restart: always
        secrets:
            - postgres_password

    odoo:
        image: xmars/odoo:17
        depends_on:
            - db
        environment:
            PASSWORD_FILE: /run/secrets/postgres_password
            HOST: db
            PORT: 5432
            USER: odoo

        ports:
            - "8069:8069"
            - "8072:8072"
        volumes:
            - ./custom-addons:/mnt/custom-addons # customize addons
            - ./etc:/etc/odoo
            - ./logs:/var/log/odoo
            - odoo-data:/var/lib/odoo
        networks:
            - frontend
            - backend
        restart: always
        secrets:
            - postgres_password

    nginx:
        image: nginx
        depends_on:
            - odoo
        volumes:
            - ./nginx:/etc/nginx/conf.d
        ports:
            - "80:80"
        networks:
            - frontend

secrets:
    postgres_password:
        file: ./postgresql/password.txt

volumes:
    odoo-data:
    postgresql-data:

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
